baseURL: https://fivestone.github.io/hugo-papermod-beginning
title: 新的 Hugo 站点 # 网站标题
theme: [PaperMod]
languageCode: 'en'

enableInlineShortcodes: true # 允许内联短码
enableEmoji: true # 允许使用 Emoji 表情，建议 true
enableRobotsTXT: true # 允许爬虫抓取到搜索引擎，建议 true
hasCJKLanguage: true # 自动检测是否包含 中文日文韩文 如果文章中使用了很多中文引号的话可以开启
paginate: 10  # 每页显示的文章数
buildDrafts: false
buildFuture: false
buildExpired: false
pygmentsUseClasses: true
# relativeURLs: true
mainsections: ["posts"]

minify:
  disableXML: true
  # minifyOutput: true

menu:
  main:
    - name: Archive
      url: archives
      weight: 5
    - name: Search
      url: search/
      weight: 10
    - name: Tags
      url: tags/
      weight: 15
    - name: about
      url: about/
      weight: 20
    - name: RSS
      url: index.xml
      weight: 25

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: 
  author: somebody

  defaultTheme: auto
  # disableThemeToggle: true
  ShowShareButtons: false
  ShowReadingTime: true
  # disableSpecial1stPost: true
  displayFullLangName: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: false
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: false # 显示目录
  TocOpen: false # 自动展开目录
  ShowFullTextinRSS: true # RSS 显示全文
  hideFooter: false # 隐藏页脚
  ShowLastMod: false #显示文章更新时间

  homeInfoParams:
    Title: "一个空的 hugo 站点"
    Content: >
      这些文字可以在 config.yml 文件里更改。

  profileMode:
    enabled: false
    title: PaperMod
    imageUrl: "#"
    imageTitle: my image
    # imageWidth: 120
    # imageHeight: 120
    buttons:
      - name: Archives
        url: archives
      - name: Tags
        url: tags

  assets:
    disableHLJS: true


